# Basic messages
killMessage: "You killed %player%"
deathMessage: "You died to %player%"
assistMessage: "ASSIST! on %player%"


killStreak: "&a%player% is on a %streak%"

# Action Bar Shit


# The message the player is sent.
# {name} shows the name of the mob or player.
# {health} shows current health of the mob or player.
# {maxhealth} shows the max health of the mob or player.
# {usestyle} will use the defined chars.
# {damager_health} get the current health of the damager.
# {damager_max} get the max health of the damager.

Health Message: '&6&l{name}: &a&l{health} / {maxhealth}'

# If enabled players with the permission 'ActionHealth.Health' will only see the action health message.

Use Permissions: false

# If set to false player will not see health messages from mobs.

Show Mob: true

# If set to false player will not see health messages from other players.

Show Player: true

# If set to true player will get the message in a delay to get 100% accurate health. Useful for plugins that add damage by reading item lore.
# This also uses more resources :(

Delay Message: false

# Style Health
Full Health Icon: "&4\u2764"
Half Health Icon: "&c\u2764"
Empty Health Icon: "&7\u2764"

# Set names. Case sensitive!
Name Change: false
Name:
  - Cow = Kuh

# ActionHealth will be disabled for any world names added below. Case sensitive!
Disabled worlds:
  - randomworld

# Disable ActionHealth in regions where PvP is denied.
Region PvP: true

# When set to true and style health is enabled this will limit the health symbols to 10.
# Currently not supporting 'Half Health Icon'
Limit Health: false