name: PitCore
description: KitX pit core
version: 1.0
main: com.kitx.PitCorePlugin
author: Parametric, IWolfZ
depend: [WorldGuard]

commands:
  perks:
    description: Pull up the perk gui
  shop:
    description: Pull up the shop gui
  stats:
    description: Shows the stats of the player
  spawn:
    description: Teleports to spawn
  setspawn:
    description: Sets spawn
  nick:
    description: Nickname yourself
  mystic:
    description: Opens the mystic gui.
  prestige:
    description: Opens the prestige gui.
  event:
    description: Used for events!